# --- NyaView Mappings Configuration File ---

ignoredPackages: []


intermediaries:
  - ==: Intermediary
    id: babric
    name: Babric
    environment: MERGED
    intermediaryName: intermediary
    clientName: client
    serverName: server
    path: babric.tiny
    format: TINY_2_FILE
  - ==: Intermediary
    id: calamus_gen2
    name: Calamus Gen2
    environment: MERGED
    intermediaryName: intermediary
    clientName: clientOfficial
    serverName: serverOfficial
    path: calamus_gen2.tiny
    format: TINY_2_FILE
  - ==: Intermediary
    id: calamus_gen1
    name: Calamus Gen1
    environment: CLIENT
    intermediaryName: intermediary
    clientName: official
    serverName: null
    path: calamus_gen1_client.tiny
    format: TINY_FILE
  - ==: Intermediary
    id: cursed_legacy
    name: Cursed Legacy
    environment: MERGED
    intermediaryName: intermediary
    clientName: client
    serverName: server
    path: cursed_legacy.tiny
    format: TINY_FILE

mappings:
  - ==: Mappings
    id: biny
    name: BINY
    environment: MERGED
    type: BABRIC
    path: biny
    format: ENIGMA_DIR
    intermediaryId: babric
  - ==: Mappings
    id: mcp_client
    name: MCP Client
    environment: CLIENT
    type: MCP
    path: mcp_client.tiny
    format: TINY_2_FILE
    intermediaryId: null
  - ==: Mappings
    id: mcp_server
    name: MCP Server
    environment: SERVER
    type: MCP
    path: mcp_server.tiny
    format: TINY_2_FILE
    intermediaryId: null
  - ==: Mappings
    id: feather_gen1
    name: Feather Gen 1
    environment: CLIENT
    type: BABRIC
    path: feather_gen1_client.tiny
    format: TINY_2_FILE
    intermediaryId: calamus_gen1
  - ==: Mappings
    id: feather
    name: Feather
    environment: MERGED
    type: BABRIC
    path: feather_gen2.tiny
    format: TINY_2_FILE
    intermediaryId: calamus_gen2
  - ==: Mappings
    id: bin-bh
    name: BIN-BH
    environment: MERGED
    type: BABRIC
    path: bin-bh
    format: ENIGMA_DIR
    intermediaryId: babric
  - ==: Mappings
    id: nostalgia
    name: Nostalgia
    environment: MERGED
    type: BABRIC
    path: nostalgia
    format: ENIGMA_DIR
    intermediaryId: babric
  - ==: Mappings
    id: flint_client
    name: Flint Client
    environment: CLIENT
    type: MCP
    path: flint_client
    format: ENIGMA_DIR
    intermediaryId: null
  - ==: Mappings
    id: flint_server
    name: Flint Server
    environment: SERVER
    type: MCP
    path: flint_server
    format: ENIGMA_DIR
    intermediaryId: null
  - ==: Mappings
    id: nya
    name: Nya
    environment: MERGED
    type: BABRIC
    path: nya
    format: ENIGMA_DIR
    intermediaryId: babric
  - ==: Mappings
    id: plasma
    name: Plasma
    environment: MERGED
    type: BABRIC
    path: plasma
    format: ENIGMA_DIR
    intermediaryId: cursed_legacy
  - ==: Mappings
    id: bin
    name: BIN
    environment: MERGED
    type: BABRIC
    path: bin
    format: ENIGMA_DIR
    intermediaryId: babric
